# Generated by Django 3.2.4 on 2021-09-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khoj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('userid', models.IntegerField()),
                ('inputvalues', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
