# Generated by Django 3.2.4 on 2021-09-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khoj', '0002_clientapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientapi',
            name='userid',
        ),
    ]
