# Generated by Django 3.2.4 on 2021-09-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khoj', '0003_remove_clientapi_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
